/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.equipo;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author iagom
 */
public class EquipoJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EquipoJFrame.class.getName());

    /**
     * Creates new form EquipoJFrame
     */
    public EquipoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        scrollLista = new javax.swing.JScrollPane();
        listaEquipos = new javax.swing.JList<>();
        panelDerecho = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        marcaLabel = new javax.swing.JLabel();
        cbMarca = new javax.swing.JComboBox<>();
        descripcionLabel = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        fotoUrlLabel = new javax.swing.JLabel();
        txtFotoUrl = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WWE Manager - Gestión de Equipos");

        splitPane.setDividerLocation(250);

        listaEquipos.setBackground(new java.awt.Color(30, 30, 30));
        listaEquipos.setForeground(new java.awt.Color(255, 255, 255));
        scrollLista.setViewportView(listaEquipos);

        splitPane.setLeftComponent(scrollLista);

        panelDerecho.setBackground(new java.awt.Color(0, 0, 0));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblId.setForeground(new java.awt.Color(150, 150, 150));
        lblId.setText("ID: Nuevo Registro");

        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Nombre del Equipo:");

        marcaLabel.setForeground(new java.awt.Color(255, 255, 255));
        marcaLabel.setText("Marca / Show:");

        descripcionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descripcionLabel.setText("Descripción del Equipo:");

        fotoUrlLabel.setForeground(new java.awt.Color(255, 255, 255));
        fotoUrlLabel.setText("URL de la Foto (Base de Datos):");

        btnNuevo.setBackground(new java.awt.Color(0, 102, 255));
        btnNuevo.setText("Nuevo");

        btnGuardar.setBackground(new java.awt.Color(116, 253, 131));
        btnGuardar.setText("Guardar");

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(marcaLabel)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionLabel)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoUrlLabel)
                    .addComponent(txtFotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(30, 30, 30)
                        .addComponent(nombreLabel)
                        .addGap(5, 5, 5)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(marcaLabel)
                .addGap(5, 5, 5)
                .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(descripcionLabel)
                .addGap(5, 5, 5)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(fotoUrlLabel)
                .addGap(5, 5, 5)
                .addComponent(txtFotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(panelDerecho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtNome() {
        return txtNome;
    }

    public JComboBox<Object> getCbMarca() {
        return cbMarca;
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public JTextField getTxtFotoUrl() {
        return txtFotoUrl;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public JLabel getLblFoto() {
        return lblFoto;
    }

    public JList<String> getListaEquipos() {
        return listaEquipos;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JButton getBtnNuevo() {
        return btnNuevo;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

public void cargarImagen(String urlStr) {
        try {
            if (urlStr != null && !urlStr.isEmpty()) {
                java.net.URL url = new java.net.URL(urlStr);
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);

                int imgAnchoOriginal = icon.getIconWidth();
                int imgAltoOriginal = icon.getIconHeight();

                int limiteAncho = lblFoto.getWidth();
                int limiteAlto = lblFoto.getHeight();

                if (limiteAncho <= 0) limiteAncho = 180;
                if (limiteAlto <= 0) limiteAlto = 180;

                double escalaAncho = (double) limiteAncho / imgAnchoOriginal;
                double escalaAlto = (double) limiteAlto / imgAltoOriginal;
                double escalaFinal = Math.min(escalaAncho, escalaAlto);

                int nuevoAncho = (int) (imgAnchoOriginal * escalaFinal);
                int nuevoAlto = (int) (imgAltoOriginal * escalaFinal);
                
                java.awt.Image img = icon.getImage().getScaledInstance(nuevoAncho, nuevoAlto, java.awt.Image.SCALE_SMOOTH);

                lblFoto.setIcon(new javax.swing.ImageIcon(img));
                lblFoto.setText("");
            } else {
                lblFoto.setIcon(null);
                lblFoto.setText("SIN FOTO");
            }
        } catch (Exception e) {
            lblFoto.setIcon(null);
            lblFoto.setText("Error Imagen");
        }
    }

    public void setFormulario(String nombre, Object marca, String descripcion, String urlFoto, String id) {
        txtNome.setText(nombre);
        txtDescripcion.setText(descripcion);
        txtFotoUrl.setText(urlFoto);
        lblId.setText("ID: " + id);
        
        if (marca != null) {
            cbMarca.setSelectedItem(marca);
        }
        cargarImagen(urlFoto);
    }

    public void limpiarFormulario() {
        txtNome.setText("");
        txtDescripcion.setText("");
        txtFotoUrl.setText("");
        lblId.setText("ID: Nuevo Registro");
        
        if (cbMarca.getItemCount() > 0) {
            cbMarca.setSelectedIndex(0);
        }
        
        lblFoto.setIcon(null);
        lblFoto.setText("");
        listaEquipos.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<Object> cbMarca;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JLabel fotoUrlLabel;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblId;
    private javax.swing.JList<String> listaEquipos;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFotoUrl;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
