package view.luchador;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author iagom
 */
public class LuchadorJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LuchadorJFrame.class.getName());
    private DefaultListModel<String> modeloLista;

    public LuchadorJFrame() {
        modeloLista = new DefaultListModel<>();
        initComponents();
        listaNombres.setModel(modeloLista);
    }

    public javax.swing.JComboBox<Object> getCbEstado() {
        return cbEstado;
    }

    public javax.swing.JComboBox<Object> getCbPeso() {
        return cbPeso;
    }

    public String getEstadoSeleccionado() {
        return cbEstado.getSelectedItem() != null ? cbEstado.getSelectedItem().toString() : "";
    }

    public String getPesoSeleccionado() {
        return cbPeso.getSelectedItem() != null ? cbPeso.getSelectedItem().toString() : "";
    }

    public String getNome() {
        return txtNome.getText();
    }

    public String getEntrada() {
        return txtEntrada.getText();
    }

    public String getFotoUrl() {
        return txtFotoUrl.getText();
    }

    public void setFormulario(String nome, String estado, String peso, String entrada, String id, String url) {
        txtNome.setText(nome);
        txtEntrada.setText(entrada);
        txtFotoUrl.setText(url);
        lblId.setText("ID: " + id);

        if (estado != null) {
            cbEstado.setSelectedItem(estado);
        }

        if (peso != null) {
            cbPeso.setSelectedItem(peso);
        }

        cargarImagen(url);
    }

    public void cargarImagen(String urlStr) {
        try {
            if (urlStr != null && !urlStr.isEmpty()) {
                java.net.URL url = new java.net.URL(urlStr);
                ImageIcon icon = new ImageIcon(url);

                int imgAnchoOriginal = icon.getIconWidth();
                int imgAltoOriginal = icon.getIconHeight();

                int limiteAncho = lblFoto.getWidth();
                int limiteAlto = lblFoto.getHeight();

                if (limiteAncho <= 0) {
                    limiteAncho = 180;
                }
                if (limiteAlto <= 0) {
                    limiteAlto = 180;
                }

                double escalaAncho = (double) limiteAncho / imgAnchoOriginal;
                double escalaAlto = (double) limiteAlto / imgAltoOriginal;

                double escalaFinal = Math.min(escalaAncho, escalaAlto);
                int nuevoAncho = (int) (imgAnchoOriginal * escalaFinal);
                int nuevoAlto = (int) (imgAltoOriginal * escalaFinal);

                Image img = icon.getImage().getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);

                lblFoto.setIcon(new ImageIcon(img));
                lblFoto.setText("");
            } else {
                lblFoto.setIcon(null);
                lblFoto.setText("SIN FOTO");
            }
        } catch (Exception e) {
            lblFoto.setIcon(null);
            lblFoto.setText("Error Imagen");
        }
    }

    public void limpiarFormulario() {
        txtNome.setText("");
        txtEntrada.setText("");
        txtFotoUrl.setText("");
        lblId.setText("Nuevo Registro");
        lblFoto.setIcon(null);

        if (cbEstado.getItemCount() > 0) {
            cbEstado.setSelectedIndex(0);
        }
        if (cbPeso.getItemCount() > 0) {
            cbPeso.setSelectedIndex(0);
        }

        listaNombres.clearSelection();
    }

    public void actualizarLista(List<String> nombres) {
        modeloLista.clear();
        nombres.forEach(modeloLista::addElement);
    }

    public int getIndexSeleccionado() {
        return listaNombres.getSelectedIndex();
    }

    public void addListaListener(ListSelectionListener lsl) {
        listaNombres.addListSelectionListener(lsl);
    }

    public void addBtnGuardarListener(ActionListener al) {
        btnGuardar.addActionListener(al);
    }

    public void addBtnEliminarListener(ActionListener al) {
        btnEliminar.addActionListener(al);
    }

    public void addBtnLimpiarListener(ActionListener al) {
        btnLimpiar.addActionListener(al);
    }
    
    public void addBtnQRListener(ActionListener al) {
        btnQR.addActionListener(al);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        scrollLista = new javax.swing.JScrollPane();
        listaNombres = new javax.swing.JList<>();
        panelDerecho = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        estadoLabel = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        pesoLabel = new javax.swing.JLabel();
        cbPeso = new javax.swing.JComboBox<>();
        cancionLabel = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFotoUrl = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnQR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WWE Manager - Gestión de Luchadores");

        splitPane.setDividerLocation(250);

        listaNombres.setBackground(new java.awt.Color(30, 30, 30));
        listaNombres.setForeground(new java.awt.Color(255, 255, 255));
        scrollLista.setViewportView(listaNombres);

        splitPane.setLeftComponent(scrollLista);

        panelDerecho.setBackground(new java.awt.Color(0, 0, 0));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblId.setForeground(new java.awt.Color(150, 150, 150));
        lblId.setText("ID: Nuevo Registro");

        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Nombre del Luchador:");

        estadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        estadoLabel.setText("Estado:");

        pesoLabel.setForeground(new java.awt.Color(255, 255, 255));
        pesoLabel.setText("Categoría de Peso:");

        cancionLabel.setForeground(new java.awt.Color(255, 255, 255));
        cancionLabel.setText("Nombre cancion:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("URL de la Foto (Base de Datos):");

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 255));
        btnLimpiar.setText("Nuevo");

        btnGuardar.setBackground(new java.awt.Color(116, 253, 131));
        btnGuardar.setText("Guardar");

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");

        btnQR.setText("QR");

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDerechoLayout.createSequentialGroup()
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreLabel)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDerechoLayout.createSequentialGroup()
                                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estadoLabel)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pesoLabel)
                                    .addComponent(cbPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cancionLabel)
                            .addComponent(jLabel5)
                            .addComponent(txtFotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDerechoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQR)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(30, 30, 30)
                        .addComponent(nombreLabel)
                        .addGap(5, 5, 5)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(estadoLabel)
                        .addGap(5, 5, 5)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(pesoLabel)
                        .addGap(5, 5, 5)
                        .addComponent(cbPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(cancionLabel)
                .addGap(5, 5, 5)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQR))
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(txtFotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(panelDerecho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnQR;
    private javax.swing.JLabel cancionLabel;
    private javax.swing.JComboBox<Object> cbEstado;
    private javax.swing.JComboBox<Object> cbPeso;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblId;
    private javax.swing.JList<String> listaNombres;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JLabel pesoLabel;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtFotoUrl;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
