/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.estadisticas;

/**
 *
 * @author iagom
 */
public class EstadisticasJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EstadisticasJFrame.class.getName());

    /**
     * Creates new form EstadisticasJFrame
     */
    public EstadisticasJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblLuchadorCombates = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLuchadorConsultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPpvFechas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMarcaLuchadores = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLuchadoresSemanales = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTitulosSemanales = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de Estadísticas - WWE Analytics");

        jLabel1.setText("Luchador con más combates PPV:");

        lblLuchadorCombates.setText("Cargando...");

        jLabel2.setText("Luchador más consultado:");

        lblLuchadorConsultado.setText("Cargando...");

        jLabel3.setText("PPV con más ediciones:");

        lblPpvFechas.setText("Cargando...");

        jLabel4.setText("Marca con más luchadores:");

        lblMarcaLuchadores.setText("Cargando...");

        jLabel5.setText("Luchadores modificados (última semana):");

        txtLuchadoresSemanales.setColumns(20);
        txtLuchadoresSemanales.setRows(5);
        jScrollPane1.setViewportView(txtLuchadoresSemanales);

        jLabel6.setText("Títulos modificados (última semana):");

        txtTitulosSemanales.setColumns(20);
        txtTitulosSemanales.setRows(5);
        jScrollPane2.setViewportView(txtTitulosSemanales);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel6))
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblLuchadorCombates)
                    .add(lblLuchadorConsultado)
                    .add(lblPpvFechas)
                    .add(lblMarcaLuchadores)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE))
                .addContainerGap(25, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(lblLuchadorCombates))
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(lblLuchadorConsultado))
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(lblPpvFechas))
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(lblMarcaLuchadores))
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 80, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE))
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 80, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE))
                .addContainerGap(25, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setLuchadorCombates(String texto) {
        this.lblLuchadorCombates.setText(texto);
    }

    public void setLuchadorConsultado(String texto) {
        this.lblLuchadorConsultado.setText(texto);
    }

    public void setPpvFechas(String texto) {
        this.lblPpvFechas.setText(texto);
    }

    public void setMarcaLuchadores(String texto) {
        this.lblMarcaLuchadores.setText(texto);
    }

    public void setLuchadoresSemanales(String texto) {
        this.txtLuchadoresSemanales.setText(texto);
    }

    public void setTitulosSemanales(String texto) {
        this.txtTitulosSemanales.setText(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLuchadorCombates;
    private javax.swing.JLabel lblLuchadorConsultado;
    private javax.swing.JLabel lblMarcaLuchadores;
    private javax.swing.JLabel lblPpvFechas;
    private javax.swing.JTextArea txtLuchadoresSemanales;
    private javax.swing.JTextArea txtTitulosSemanales;
    // End of variables declaration//GEN-END:variables
}
