package view;

import java.awt.event.ActionListener;


/**
 *
 * @author iagom
 */
public class MainJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        configurarFondo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        marcaJMenuItem = new javax.swing.JMenuItem();
        equipoJMenuItem = new javax.swing.JMenuItem();
        luchadorJMenuItem = new javax.swing.JMenuItem();
        ppvJMenuItem = new javax.swing.JMenuItem();
        tituloJMenuItem = new javax.swing.JMenuItem();
        estadisiticasMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoLabel.setText("");

        jMenu1.setText("Menu");

        marcaJMenuItem.setText("Marca");
        marcaJMenuItem.addActionListener(this::marcaJMenuItemActionPerformed);
        jMenu1.add(marcaJMenuItem);

        equipoJMenuItem.setText("Equipo");
        jMenu1.add(equipoJMenuItem);

        luchadorJMenuItem.setText("Luchador");
        jMenu1.add(luchadorJMenuItem);

        ppvJMenuItem.setText("PPV");
        jMenu1.add(ppvJMenuItem);

        tituloJMenuItem.setText("Titulo");
        jMenu1.add(tituloJMenuItem);

        estadisiticasMenuItem.setText("Estadisticas");
        jMenu1.add(estadisiticasMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setText("Salir");
        jMenu1.add(quitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(fondoLabel)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(fondoLabel)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcaJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaJMenuItemActionPerformed

    private void configurarFondo() {
        this.getContentPane().setBackground(java.awt.Color.BLACK);
        fondoLabel = new javax.swing.JLabel();

        try {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/res/WWE-Logo.png"));
            java.awt.Image img = icon.getImage().getScaledInstance(400, 400, java.awt.Image.SCALE_SMOOTH);
            fondoLabel.setIcon(new javax.swing.ImageIcon(img));
        } catch (Exception e) {
        }

        // 4. Centrar el logo en el label
        fondoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoLabel.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

        this.setLayout(new java.awt.BorderLayout());
        this.add(fondoLabel, java.awt.BorderLayout.CENTER);

        this.pack();
        this.setSize(900, 600);
        this.setLocationRelativeTo(null);
    }

    public void addMarcaListener(ActionListener al) {
        marcaJMenuItem.addActionListener(al);
    }

    public void addEquipoListener(ActionListener al) {
        equipoJMenuItem.addActionListener(al);
    }

    public void addLuchadorListener(ActionListener al) {
        luchadorJMenuItem.addActionListener(al);
    }

    public void addPPVListener(ActionListener al) {
        ppvJMenuItem.addActionListener(al);
    }

    public void addTituloListener(ActionListener al) {
        tituloJMenuItem.addActionListener(al);
    }

    public void addQuitListener(ActionListener al) {
        quitMenuItem.addActionListener(al);
    }

    public void addEstadisticasListener(ActionListener al) {
        estadisiticasMenuItem.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem equipoJMenuItem;
    private javax.swing.JMenuItem estadisiticasMenuItem;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem luchadorJMenuItem;
    private javax.swing.JMenuItem marcaJMenuItem;
    private javax.swing.JMenuItem ppvJMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenuItem tituloJMenuItem;
    // End of variables declaration//GEN-END:variables
}
