package view.titulo;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author iagom
 */
public class TituloJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TituloJFrame.class.getName());

    /**
     * Creates new form tituloJFrame
     */
    public TituloJFrame() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(18, 18, 18));
        lblId.setForeground(new java.awt.Color(200, 200, 200));
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        scrollLista = new javax.swing.JScrollPane();
        listaTitulos = new javax.swing.JList<>();
        panelDerecho = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        estadoLabel = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        dataLabel = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        fotoUrlLabel = new javax.swing.JLabel();
        txtFotoUrl = new javax.swing.JTextField();
        chkMaximo = new javax.swing.JCheckBox();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WWE Manager - Gestión de Títulos");

        splitPane.setDividerLocation(250);

        scrollLista.setViewportView(listaTitulos);

        splitPane.setLeftComponent(scrollLista);

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblId.setForeground(new java.awt.Color(150, 150, 150));
        lblId.setText("ID: Nuevo Registro");

        nombreLabel.setText("Nombre del Título:");

        estadoLabel.setText("Estado:");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activo", "vacante", "inactivo" }));

        dataLabel.setText("Fecha de Vigencia:");

        fotoUrlLabel.setText("URL Foto/Logo:");

        chkMaximo.setText("Es Título Máximo (Main Event)");
        chkMaximo.setOpaque(true);

        btnNuevo.setBackground(new java.awt.Color(0, 102, 255));
        btnNuevo.setText("Nuevo");

        btnGuardar.setBackground(new java.awt.Color(116, 253, 131));
        btnGuardar.setText("Guardar");

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoLabel)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataLabel)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fotoUrlLabel)
                    .addComponent(txtFotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMaximo)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(30, 30, 30)
                        .addComponent(nombreLabel)
                        .addGap(5, 5, 5)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(estadoLabel)
                        .addGap(5, 5, 5)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(dataLabel)
                        .addGap(5, 5, 5)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(fotoUrlLabel)
                .addGap(5, 5, 5)
                .addComponent(txtFotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkMaximo)
                .addGap(42, 42, 42)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(panelDerecho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    public javax.swing.JButton getBtnGuardar() {
        return btnGuardar;
    }

    public javax.swing.JButton getBtnNuevo() {
        return btnNuevo;
    }

    public javax.swing.JCheckBox getChkMaximo() {
        return chkMaximo;
    }

    public javax.swing.JComboBox<String> getComboEstado() {
        return comboEstado;
    }

    public javax.swing.JLabel getLblId() {
        return lblId;
    }

    public javax.swing.JLabel getLblFoto() {
        return lblFoto;
    }

    public javax.swing.JList getListaTitulos() {
        return listaTitulos;
    }

    public javax.swing.JTextField getTxtData() {
        return txtData;
    }

    public javax.swing.JTextField getTxtFotoUrl() {
        return txtFotoUrl;
    }

    public javax.swing.JTextField getTxtNome() {
        return txtNome;
    }

    public void cargarImagen(String urlStr) {
        try {
            if (urlStr != null && !urlStr.isEmpty()) {
                java.net.URL url = new java.net.URL(urlStr);
                ImageIcon icon = new ImageIcon(url);

                int imgAnchoOriginal = icon.getIconWidth();
                int imgAltoOriginal = icon.getIconHeight();

                int limiteAncho = lblFoto.getWidth();
                int limiteAlto = lblFoto.getHeight();

                if (limiteAncho <= 0) {
                    limiteAncho = 180;
                }
                if (limiteAlto <= 0) {
                    limiteAlto = 180;
                }

                double escalaAncho = (double) limiteAncho / imgAnchoOriginal;
                double escalaAlto = (double) limiteAlto / imgAltoOriginal;

                double escalaFinal = Math.min(escalaAncho, escalaAlto);

                int nuevoAncho = (int) (imgAnchoOriginal * escalaFinal);
                int nuevoAlto = (int) (imgAltoOriginal * escalaFinal);

                Image img = icon.getImage().getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);

                lblFoto.setIcon(new ImageIcon(img));
                lblFoto.setText("");
            } else {
                lblFoto.setIcon(null);
                lblFoto.setText("SIN FOTO");
            }
        } catch (Exception e) {
            lblFoto.setIcon(null);
            lblFoto.setText("Error Imagen");
        }
    }

    public void setFormulario(String nome, String estado, String dataVigencia, String urlFoto, String id, boolean esMaximo) {
        txtNome.setText(nome);
        txtData.setText(dataVigencia);
        txtFotoUrl.setText(urlFoto);
        lblId.setText("ID: " + id);
        chkMaximo.setSelected(esMaximo);

        if (estado != null) {
            comboEstado.setSelectedItem(estado.toLowerCase().trim());
        }

        cargarImagen(urlFoto);
    }

    public void limpiarFormulario() {
        txtNome.setText("");
        txtData.setText("");
        txtFotoUrl.setText("");
        lblId.setText("ID: Nuevo Registro");
        chkMaximo.setSelected(false);

        if (comboEstado.getItemCount() > 0) {
            comboEstado.setSelectedIndex(0);
        }

        lblFoto.setIcon(null);
        lblFoto.setText("");
        listaTitulos.clearSelection();
    }

    public String getNome() {
        return txtNome.getText();
    }

    public String getEstadoSeleccionado() {
        return comboEstado.getSelectedItem() != null ? comboEstado.getSelectedItem().toString() : "";
    }

    public String getFotoUrl() {
        return txtFotoUrl.getText();
    }

    public boolean isMaximoSelected() {
        return chkMaximo.isSelected();
    }

    public int getIndexSeleccionado() {
        return listaTitulos.getSelectedIndex();
    }

    public void actualizarLista(java.util.List<String> nombres) {
        javax.swing.DefaultListModel<String> nuevoModelo = new javax.swing.DefaultListModel<>();
        if (nombres != null) {
            nombres.forEach(nuevoModelo::addElement);
        }
        listaTitulos.setModel((javax.swing.ListModel) nuevoModelo);
    }

    // ====================================================================
    // MÉTODOS DE SUSCRIPCIÓN DE LISTENERS PARA EL CONTROLADOR
    // ====================================================================
    public void addListaListener(javax.swing.event.ListSelectionListener lsl) {
        listaTitulos.addListSelectionListener(lsl);
    }

    public void addBtnGuardarListener(java.awt.event.ActionListener al) {
        btnGuardar.addActionListener(al);
    }

    public void addBtnEliminarListener(java.awt.event.ActionListener al) {
        btnEliminar.addActionListener(al);
    }

    public void addBtnNuevoListener(java.awt.event.ActionListener al) {
        btnNuevo.addActionListener(al);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkMaximo;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel fotoUrlLabel;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblId;
    private javax.swing.JList<String> listaTitulos;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtFotoUrl;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
