
package view.marca;

import model.Marca;

/**
 *
 * @author iagom
 */
public class MarcaJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MarcaJFrame.class.getName());

    /**
     * Creates new form marcaJFrame
     */
    public MarcaJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        scrollLista = new javax.swing.JScrollPane();
        listaMarcas = new javax.swing.JList<>();
        panelDerecho = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        urlLabel = new javax.swing.JLabel();
        txtLogoUrl = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WWE Manager - Gestión de Marcas");

        splitPane.setDividerLocation(250);

        scrollLista.setViewportView(listaMarcas);

        splitPane.setLeftComponent(scrollLista);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblId.setForeground(new java.awt.Color(150, 150, 150));
        lblId.setText("ID: Nuevo Registro");

        nombreLabel.setText("Nombre de la Marca:");

        urlLabel.setText("URL del Logo:");

        btnNuevo.setBackground(new java.awt.Color(0, 102, 255));
        btnNuevo.setText("Nuevo");

        btnGuardar.setBackground(new java.awt.Color(116, 253, 131));
        btnGuardar.setText("Guardar");

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(urlLabel)
                    .addComponent(txtLogoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(30, 30, 30)
                        .addComponent(nombreLabel)
                        .addGap(5, 5, 5)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(urlLabel)
                .addGap(5, 5, 5)
                .addComponent(txtLogoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(panelDerecho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JList<Marca> getListaMarcas() {
        return (javax.swing.JList<model.Marca>) (Object) listaMarcas;
    }

    public javax.swing.JButton getBtnGuardar() {
        return btnGuardar;
    }

    public javax.swing.JButton getBtnNuevo() {
        return btnNuevo;
    }

    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    public javax.swing.JTextField getTxtNome() {
        return txtNome;
    }

    public javax.swing.JTextField getTxtLogoUrl() {
        return txtLogoUrl;
    }

    public javax.swing.JLabel getLblId() {
        return lblId;
    }

    public javax.swing.JLabel getLblLogo() {
        return lblLogo;
    }

    public void actualizarLogo(String url) {
        try {
            if (url != null && !url.isEmpty()) {
                java.net.URL imgUrl = new java.net.URL(url);
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);

                java.awt.Image img = icon.getImage().getScaledInstance(
                        lblLogo.getWidth(), 
                        lblLogo.getHeight(), 
                        java.awt.Image.SCALE_SMOOTH
                );
                lblLogo.setIcon(new javax.swing.ImageIcon(img));
                lblLogo.setText("");
            } else {
                lblLogo.setIcon(null);
                lblLogo.setText("Sin Logo");
            }
        } catch (Exception e) {
            lblLogo.setIcon(null);
            lblLogo.setText("Error Logo");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JList<String> listaMarcas;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtLogoUrl;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel urlLabel;
    // End of variables declaration//GEN-END:variables
}
