/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.ppv;

/**
 *
 * @author iagom
 */
public class PpvJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PpvJFrame.class.getName());

    /**
     * Creates new form ppvJFrame
     */
    public PpvJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        scrollLista = new javax.swing.JScrollPane();
        listaPPVs = new javax.swing.JList<>();
        panelDerecho = new javax.swing.JPanel();
        lblPoster = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        grupoLabel = new javax.swing.JLabel();
        cbGrupoPPV = new javax.swing.JComboBox<>();
        btnNuevoGrupo = new javax.swing.JButton();
        urlLabel = new javax.swing.JLabel();
        txtPosterUrl = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVerCombates = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WWE Manager - Gestión de PPVs");

        splitPane.setDividerLocation(250);

        listaPPVs.setBackground(new java.awt.Color(30, 30, 30));
        listaPPVs.setForeground(new java.awt.Color(255, 255, 255));
        scrollLista.setViewportView(listaPPVs);

        splitPane.setLeftComponent(scrollLista);

        panelDerecho.setBackground(new java.awt.Color(18, 18, 18));

        lblPoster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblId.setForeground(new java.awt.Color(150, 150, 150));
        lblId.setText("ID: Nuevo PPV");

        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Nombre del Evento:");

        grupoLabel.setForeground(new java.awt.Color(255, 255, 255));
        grupoLabel.setText("Grupo de PPV:");

        btnNuevoGrupo.setText("+");

        urlLabel.setForeground(new java.awt.Color(255, 255, 255));
        urlLabel.setText("URL del Póster:");

        btnNuevo.setBackground(new java.awt.Color(52, 152, 219));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");

        btnGuardar.setBackground(new java.awt.Color(46, 204, 113));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");

        btnEliminar.setBackground(new java.awt.Color(231, 76, 60));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");

        btnVerCombates.setBackground(new java.awt.Color(0, 51, 179));
        btnVerCombates.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerCombates.setForeground(new java.awt.Color(255, 255, 255));
        btnVerCombates.setText("Ver Combates");

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(grupoLabel)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(cbGrupoPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnNuevoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(urlLabel)
                    .addComponent(txtPosterUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnVerCombates, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(30, 30, 30)
                        .addComponent(nombreLabel)
                        .addGap(5, 5, 5)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(grupoLabel)
                .addGap(5, 5, 5)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGrupoPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(urlLabel)
                .addGap(5, 5, 5)
                .addComponent(txtPosterUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerCombates, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(panelDerecho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    public javax.swing.JButton getBtnGuardar() {
        return btnGuardar;
    }

    public javax.swing.JButton getBtnNuevo() {
        return btnNuevo;
    }

    public javax.swing.JButton getBtnNuevoGrupo() {
        return btnNuevoGrupo;
    }

    public javax.swing.JButton getBtnVerCombates() {
        return btnVerCombates;
    }

    public javax.swing.JComboBox<Object> getCbGrupoPPV() {
        return cbGrupoPPV;
    }

    public javax.swing.JLabel getLblId() {
        return lblId;
    }

    public javax.swing.JLabel getLblPoster() {
        return lblPoster;
    }

    public javax.swing.JList<model.PPV> getListaPPVs() {
        return listaPPVs;
    }

    public javax.swing.JTextField getTxtNome() {
        return txtNome;
    }

    public javax.swing.JTextField getTxtPosterUrl() {
        return txtPosterUrl;
    }

    public void actualizarPoster(String urlStr) {
        cargarImagen(urlStr);
    }

    public void cargarImagen(String urlStr) {
        try {
            if (urlStr != null && !urlStr.trim().isEmpty()) {
                java.net.URL url = new java.net.URL(urlStr);
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);

                int imgAnchoOriginal = icon.getIconWidth();
                int imgAltoOriginal = icon.getIconHeight();

                int limiteAncho = lblPoster.getWidth();
                int limiteAlto = lblPoster.getHeight();

                if (limiteAncho <= 0) {
                    limiteAncho = 180;
                }
                if (limiteAlto <= 0) {
                    limiteAlto = 180;
                }

                double escalaAncho = (double) limiteAncho / imgAnchoOriginal;
                double escalaAlto = (double) limiteAlto / imgAltoOriginal;
                double escalaFinal = Math.min(escalaAncho, escalaAlto);

                int nuevoAncho = (int) (imgAnchoOriginal * escalaFinal);
                int nuevoAlto = (int) (imgAltoOriginal * escalaFinal);

                java.awt.Image img = icon.getImage().getScaledInstance(nuevoAncho, nuevoAlto, java.awt.Image.SCALE_SMOOTH);
                lblPoster.setIcon(new javax.swing.ImageIcon(img));
                lblPoster.setText("");
            } else {
                lblPoster.setIcon(null);
                lblPoster.setText("SIN PÓSTER");
            }
        } catch (Exception e) {
            lblPoster.setIcon(null);
            lblPoster.setText("Error Imagen");
        }
    }

    public void setFormulario(String nombre, String urlFoto, String id, Object grupoPPV) {
        txtNome.setText(nombre);
        txtPosterUrl.setText(urlFoto);
        lblId.setText("ID: " + id);

        if (grupoPPV != null) {
            cbGrupoPPV.setSelectedItem(grupoPPV);
        } else if (cbGrupoPPV.getItemCount() > 0) {
            cbGrupoPPV.setSelectedIndex(0);
        }
        cargarImagen(urlFoto);
    }

    public void limpiarFormulario() {
        txtNome.setText("");
        txtPosterUrl.setText("");
        lblId.setText("ID: Nuevo PPV");
        if (cbGrupoPPV.getItemCount() > 0) {
            cbGrupoPPV.setSelectedIndex(0);
        }
        lblPoster.setIcon(null);
        lblPoster.setText("");
        listaPPVs.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevoGrupo;
    private javax.swing.JButton btnVerCombates;
    private javax.swing.JComboBox<Object> cbGrupoPPV;
    private javax.swing.JLabel grupoLabel;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JList<model.PPV> listaPPVs;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPosterUrl;
    private javax.swing.JLabel urlLabel;
    // End of variables declaration//GEN-END:variables
}
